### ISSUE TITLE
Travis CI automation: investigate why no tests were executed for linked-list exercise

### ISSUE THREAD

**Issue by m-a-ge** [exercism/groovy#106]
Judging by logs for Build #194 https://travis-ci.org/exercism/groovy/builds/322106184 no tests were executed for `linked-list` exercise.
Looks like `Spec` file is broken right now as well.

This should be investigated

**Comment by m-a-ge** [comment]
Looks like the issue was fixed in https://github.com/exercism/groovy/pull/108
But still, I have to revisit automation script to figure out what was the root cause of the issue

**Comment by amscotti** [comment]
Looking at the last builds, this doesn't seem to be an issue any more. If it pops up again, we can reopen the issue.
