### ISSUE TITLE
phone-number: test suite does not match problem description

### ISSUE THREAD

**Issue by chuckwondo** [exercism/groovy#110]
In the `README.md` for `phone-number`, there is the following:

> The format is usually represented as
> 
> (NXX)-NXX-XXXX
> 
> where N is any digit from 2 through 9 and X is any digit from 0 through 9.

However, there are multiple tests in which `N` is `1`, in clear contradiction to the statement above, yet the phone number is considered valid.

It seems to me that the test cases should be corrected to adhere to the format described above, and that perhaps additional cases should be added to fail when `N` is `1` in either of the indicated positions.

I'd be glad to contribute if there's consensus that this is an issue, although perhaps this is prevalent across all of the languages. I know this problem in Python suffers similarly (although the test cases differ).

**Comment by chuckwondo** [comment]
I believe I see the issue. It appears that at some point the [canonical data for phone-number](https://github.com/exercism/problem-specifications/blob/master/exercises/phone-number/canonical-data.json) was updated to match the problem description, but that at least the Groovy test suite (likely others as well) was not updated to match the change in canonical data.

Shall I fix this for Groovy and submit a pull request?

**Comment by m-a-ge** [comment]
@chuckwondo thanks for raising the issue

> Shall I fix this for Groovy and submit a pull request?
That would be awesome!

**Comment by chuckwondo** [comment]
Great. I plan to take care of this over the weekend.
