### ISSUE TITLE
Need to correct the formating on all the tests.

### ISSUE THREAD

**Issue by chriseyre2000** [exercism/groovy#154]
Spock tests should be indented within the given/when/then

The where tables should use || to split inputs from expectations.

**Comment by amscotti** [comment]
Hi @chriseyre2000, thanks for posting the issue! Looking over the [Spock docs](http://spockframework.org/spock/docs/1.3/data_driven_testing.html#_syntactic_variations), I see the `||` being used, I'll make this update this weekend to start using `||` for the expectations. This is a good idea, thanks for pointing this out to me!

As far as the indentation, I don't see any example of this in documentation or the [example project for Spock](https://github.com/spockframework/spock-example/blob/master/src/test/groovy/HelloSpockSpec.groovy), actually all the examples that I've seen do not show indentation for items in blocks. Right now I have been using the formatting in IntelliJ to keep the project consistent, and it seems to prefer no indentation. To be able to keep the project formatted and to keep inline with what I see for the Spock documentation I'm not going to add indentation.

**Comment by chriseyre2000** [comment]
You can fix Intellij:

https://stackoverflow.com/questions/19678129/indenting-spaces-layout-after-a-label-in-intellij-with-groovy

This has been may experience of using spock in production (all experienced Groovy developers that I have met prefer this style).

**Comment by amscotti** [comment]
It's not just about fixing IntelliJ, It's also looking at the Spock documentation and examples and not seeing indentations. I would like to keep in line with they are doing and use defaults when we can. This will make it easier for people who want to contribute to the track.

I also think as the track will most likely not have many experienced Groovy developers, keeping in line with what we see in the Spock documentation and examples maybe best for the students as they learn Groovy.
