### ISSUE TITLE
High-scores exercise: personalTopThree and mutating the list

### ISSUE THREAD

**Issue by glennj** [exercism/groovy#211]
I see most solutions for high-scores doing something like this:
```groovy
    this.scores.sort { -it }.take(3)
```
This mutates the instance variable in-place, breaking the validity of the `latest()` method. What is needed is http://docs.groovy-lang.org/latest/html/groovy-jdk/java/lang/Iterable.html#sort(boolean,%20groovy.lang.Closure)
```groovy
    this.scores.sort(false) { -it }.take(3)
```

I propose to add a new test that: creates an instance, does the top 3 *then* asks for the latest:
```groovy
    def "Personal top three does not mutate"() {
        given:
        def hs = new HighScores(scores)
        def top3 = hs.personalTopThree()

        expect:
        hs.latest() == expected

        where:
        scores           || expected
        [40, 20, 10, 30] || 30
    }
```
If there is interest in this, I'll submit a pull request.

**Comment by amscotti** [comment]
Sounds good to me!

**Comment by glennj** [comment]
PR #212
