### ISSUE TITLE
Update config.json to match new specification

### ISSUE THREAD

**Issue by kytrinyx** [exercism/groovy#27]
- [x] Replace the _problems_ array with an _exercises_ key containing an array of objects, where _difficulty_ is 1 and _topics_ is empty.
- [x] Update the difficulty settings to reflect a more accurate guess.
- [x] Add topics (perhaps one-by-one, in separate pull requests, in order to have useful discussions about each exercise).

For the past three years, the ordering of exercises has been done based on gut feelings and wild guesses. As a result, the progression of the exercises has been somewhat haphazard.

In the past few months maintainers of several tracks have invested a great deal of time in analyzing what concepts various exercises require, and then reordering the tracks as a result of that analysis.

It would be useful to bake this data into the track configuration so that we can adjust it over time as we learn more about each exercise.

To this end, we've decided to add a new key _exercises_ in the config.json file, and deprecate the `problems` key.

See exercism/discussions#60 for details about this decision.

Note that we will **not** be removing the `problems` key at this time, as this would break the website and a number of tools.

The process for deprecating the old `problems` array will be:
- Update all of the track configs to contain the new _exercises_ key, with whatever data we have.
- Simultaneously change the website and tools to support both formats.
- Once all of the tracks have added the _exercises_ key, remove support for the old key in the site and tools.
- Remove the old key from all of the track configs.

In the new format, each exercise is a JSON object with three properties:
- _slug_: the identifier of the exercise
- _difficulty_: a number from 1 to 10 where 1 is the easiest and 10 is the most difficult
- _topics_: an array of strings describing topics relevant to the exercise. We maintain
  a list of common topics at https://github.com/exercism/x-common/blob/master/TOPICS.txt. Do not feel like you need to restrict yourself to this list;
  it's only there so that we don't end up with 20 variations on the same topic. Each
  language is different, and there will likely be topics specific to each language that will
  not make it onto the list.

The _difficulty_ rating can be a very rough estimate.

The _topics_ array can be empty if this analysis has not yet been done.

Example:

```
"exercises": [
  {
    "slug": "hello-world" ,
    "difficulty": 1,
    "topics": [
        "control-flow (if-statements)",
        "optional values",
        "text formatting"
    ]
  },
  {
    "difficulty": 3,
    "slug": "anagram",
    "topics": [
        "strings",
        "filtering"
    ]
  },
  {
    "difficulty": 10,
    "slug": "forth",
    "topics": [
        "parsing",
        "transforming",
        "stacks"
    ]
  }
]
```

**Comment by Dispader** [comment]
Looks like #30 may bring us back up to being in as good a shape as the Ruby track.

Would we want to flesh out the topics and difficulty, or should that be another issue ([as it looks like it is in the Ruby track](https://github.com/exercism/xruby/issues/481))?

**Comment by kytrinyx** [comment]
I don't see any reason to open a new issue, since we have this one. I'll change the numbered list to a task list, though, which should make it clear what has been done.

**Comment by Dispader** [comment]
Note to Self: the [xpascal track has some values which may be sensible defaults](https://github.com/exercism/xpascal/blob/master/config.json) to consider when judging Groovy exercises.

**Comment by Dispader** [comment]
(Also, apologies for my sins here— I did merge up Pull #40 , but really should have rebased it as a single commit.  I *don't* know if it actually checks us off for initial ratings, but I think we've improved from "everything's a difficulty 1." 😅  )

It looks like we could use some separate Pulls for topics.  Barring anybody else jumping in, I'd like to do these one at a time in a walkthrough of each exercise.

However— our translations to Spock specifications for tests are good, but in a half-completed state, and I think I'd like to make all the available exercises consistent.  In case folks want to start walking the experimental Groovy track, I'd feel better if they were a bit less surprised by the test transition from Spock to JUnit.

**Comment by kytrinyx** [comment]
To be fair, topics aren't used by anything... yet. So if they're not going to help you organize the track, it's totally fine to leave them all blank.

**Comment by m-a-ge** [comment]
Is this issue still relevant? 
Judging by the current version of [config.json](https://github.com/exercism/groovy/blob/master/config.json) everything looks Ok, or I'm missing something?

**Comment by kytrinyx** [comment]
There are no topics, I think, but other than that this is fine.

**Comment by m-a-ge** [comment]
@kytrinyx, I would love to see this track launched, but I am not an expert in Groovy.

I can add a general list of topics mentioned [here](https://github.com/exercism/meta/issues/83#issuecomment-321279731). Will it be enough to resolve this issue?

**Comment by kytrinyx** [comment]
@m-a-ge Yes, that would be fantastic!

**Comment by kytrinyx** [comment]
> I would love to see this track launched

I really appreciate your help on this. Would you be interested in having commit on the repository?  I'd love to have another person onboard who cares about this track. I would be here to help answer any questions that you have, review pull requests, etc.

**Comment by m-a-ge** [comment]
> Would you be interested in having commit on the repository?
Yes, I would love to help

**Comment by kytrinyx** [comment]
> I would love to help

🌻 awesome, thank you! I've sent you an invite.

**Comment by m-a-ge** [comment]
@kytrinyx, thank you for the trust! 
I've added PR for topics as promised and also created some issues which I will hopefully resolve tomorrow

**Comment by m-a-ge** [comment]
To completely resolve this issue we have to decide on exercise difficulty. 
It's a tricky topic, but I think, in general, the exercise difficulty in Groovy should be lower than in Java :trollface: (see what I did there?)

To be honest it's hard for me to decide. @Dispader, what do you think?

Btw, I ticked off the topics issue

**Comment by Dispader** [comment]
I just ticked off the 'difficulty' item: I think @m-a-ge has made a great first pass, here— and I believe that we're close enough to call this issue closed.

🤗 , Everyone!
