### ISSUE TITLE
CIS-CAT warning: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass

### ISSUE THREAD

**Issue by Ro42** [exercism/groovy#309]
Hi,
i really don´t know if this is the right place, but i will give it a try.

When i try to run the Assessor-CLI from CIS-CAT 
(https://www.cisecurity.org/) i get the following error message, that tells me completly nothing ;-)

Excuse me if this is the wrong auditorium for this problem.

Rgds Roland

roland@RoMac3 Assessor-CLI % Assessor-CLI.sh 
zsh: command not found: Assessor-CLI.sh
roland@RoMac3 Assessor-CLI % pwd
/Users/roland/Downloads/Assessor-CLI
roland@RoMac3 Assessor-CLI % /Users/roland/Downloads/Assessor-CLI/Assessor-CLI.sh 
readlink: illegal option -- f
usage: readlink [-n] [file ...]
**WARNING: An illegal reflective access operation has occurred**
**WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass** (file:/Users/roland/Downloads/Assessor-CLI/lib/groovy-2.5.14.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
19:38:34.002 [main] DEBUG org.cisecurity.assessor.cli.Utilities - Discovered path --> /Users/roland/Downloads/Assessor-CLI/Assessor-CLI.jar
19:38:34.008 [main] DEBUG org.cisecurity.assessor.cli.Utilities - Discovered jar path --> /Users/roland/Downloads/Assessor-CLI/Assessor-CLI.jar

--------------------------------------------------------------------------------------
   ,o88888o.    8888    d888888o.          ,o88888o.           8.    8888888888888888 
  8888    `88.  8888  .`8888:' `88.       8888    `88.        .88.         8888       
,88888      `8. 8888  8.`8888.   Y8     ,88888      `8.      .8888.        8888       
888888          8888  `8.`8888.         888888              .`88888.       8888       
888888          8888   `8.`8888.   888  888888             .8.`88888.      8888       
888888          8888    `8.`8888.  888  888888            .8`8.`88888.     8888       
888888          8888     `8.`8888.      888888           .8' `8.`88888.    8888       
`88888      .8' 8888 8b   `8.`8888.     `88888      .8' .8'   `8.`88888.   8888       
  8888    ,88'  8888 `8b.  ;8.`8888       8888    ,88' .888888888.`88888.  8888       
   `888888P'    8888  `Y8888P ,88P'        `888888P'  .8'       `8.`88888. 8888       
--------------------------------------------------------------------------------------
         Welcome to CIS-CAT Pro Assessor; built on 01/26/2022 14:27 PM
--------------------------------------------------------------------------------------
  This is the Center for Internet Security Configuration Assessment Tool, v4.14.0
          At any time during the selection process, enter 'q!' to exit.
--------------------------------------------------------------------------------------
		
Verifying application

usage: Assessor-CLI.[bat|sh] -[options] <extras>

**Comment by NobbZ** [comment]
This issue tracker is not related to CIS-CAT, it is about the groovy track on the exercism.org website.

Please open a request for support through the developers/publishers means.
