### ISSUE TITLE
Rename exercise files to match exercise name

### ISSUE THREAD

**Issue by kytrinyx** [exercism/groovy#67]
We have a number of exercises that have names that do not match the exercise name.

E.g. the exercise `word-count` has the file names `Phrase.groovy` and `PhraseSpec.groovy`. This means that we cannot generate the correct command to run automatically.

In order to make it possible to generate this, the filenames should be based on the exercise name. So `word-count` should have the filenames `WordCount.groovy` and `WordCountSpec.groovy`.

It would also make sense to update the class names in the exercises to match the filenames.

These are the exercises in question.

- [x] difference-of-squares
- [x] nth-prime
- [x] rna-transcription
- [x] robot-name
- [x] roman-numerals
- [x] word-count

#64 should probably be merged before this issue gets addressed, since it adds more files that need to be renamed to address this issue.

**Comment by m-a-ge** [comment]
Thanks for creating the issue!
I'll fix it later today

**Comment by m-a-ge** [comment]
I've also checked other  exercises and found some inconsistency in `leap` and corrected it as well.

PR #69 has been created.
@kytrinyx, please take a look when you have a minute
