### ISSUE TITLE
Prepare the track for Nextercism

### ISSUE THREAD

**Issue by m-a-ge** [exercism/groovy#73]
Action items from https://github.com/exercism/v2-feedback/blob/master/README.md

The two most important things are:

- [x] add or edit introductory copy
- [x] rework exercises for the new site
  - [x] choose core exercises
  - [x] decide which exercises get unlocked by a core exercise
  - [x]  add topics to exercise metadata
  - [x] update difficulty ratings for exercises

For a track to be included in the new site, it must have:

- [x] introductory copy
- [x] exercise metadata (topics, difficulties)
- [x] a core exercise progression consisting of 8-20 exercises
- [x] 2-3 optional introductory exercises (core: false, unlocked by: false)
- [ ] committed mentors

We would also really love it if each core exercise unlocks at least one optional exercise.

It seems like significant amount of work

**Comment by m-a-ge** [comment]
I've added topics in https://github.com/exercism/groovy/pull/61

**Comment by Raibaz** [comment]
Hi, is there any way I can help on this?

**Comment by m-a-ge** [comment]
@Raibaz sure, I'm glad that some else is willing to help.
Could you please take a look at https://github.com/exercism/groovy/pull/95 and give your opinion? That PR is crucial in establishing good practices for the track.

**Comment by m-a-ge** [comment]
@Raibaz I guess the focus now is to introduce our core exercises. I believe using those used in Java is a good enough option. So, we should implement them all and add to the track.
After that we can figure out in what order they will be served to the user and so on

**Comment by amscotti** [comment]
Closing this issue as Groovy is now launched on the site with the merging of PR #150
