### ISSUE TITLE
Decide on track curriculum 

### ISSUE THREAD

**Issue by lastRoot** [exercism/groovy#88]
We should decide on track curriculum and change `config.json` accordingly. By that I mean we should decide on the following things (can be converted to separate issues):
* [ ] exercise topics, 
* [ ] exercise difficulty, 
* [ ] what are the core exercises
* [ ] what unlocks what
* [ ] add helpful exercise hints describing best practices etc

List of language topics I think we should cover to give a learner a good sense of the language (feel free to extend):
* [ ] Numbers and Strings
  * [ ] Integer and Floating Point Types
  * [ ] Operator Overloading
  * [ ] Strings and Groovy Strings
  * [ ] Regular Expressions
  * [ ] Strings formatting
* [ ] Classes
  * [ ] Plain Old Groovy Objects (POGOs)
* [ ] Collections
  * [ ] Groovy Ranges
  * [ ] Lists
  * [ ] Map
  * [ ] Set
* [ ] Closures
  * [ ] Iterating Using Closures
* [ ]  Runtime Metaprogramming
* [ ] AST Transformations

It would be a good idea to create a separate `.md` file describing what exercise is suitable for practicing particular topic above assuming it has good hints explaining Groovy specific features and giving other hints.

**Comment by amscotti** [comment]
Closing this issue as I believe it was created before V2 and may no longer be relevant
