### ISSUE TITLE
Launch planning

### ISSUE THREAD

**Issue by kytrinyx** [exercism/groovy#9]
_Note: the launch checklist was woefully outdated, since this got created over two years ago, so I deleted it._

Let's use the launch guide as a starting point for discussions about what to do next: https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md

**Comment by m-a-ge** [comment]
thanks to @catb0t we have logo icon, complete this step

**Comment by kytrinyx** [comment]
@m-a-ge yepp! And in the nextercism, we're redoing all the logos. I'll make sure the designer knows that groovy will be launching very soon so she can do a logo for it.

**Comment by m-a-ge** [comment]
I went over docs once again and I think they look Ok. 
Ticked them off

@kytrinyx, how one can become a track mentor? Are there any requirements?

**Comment by kytrinyx** [comment]
You've fulfilled the requirements by showing up and doing work enthusiastically and graciously! Also, you became a maintainer last week when I gave you commit to the repo.

Go ahead and add yourself to the `config/maintainers.json` file https://github.com/exercism/groovy/blob/master/config/maintainers.json

**Comment by kytrinyx** [comment]
Wait. Clearly I can't read. That says track mentor, not track maintainer. I'll add you right now!

**Comment by kytrinyx** [comment]
OK, you should be all set as a track mentor.

**Comment by m-a-ge** [comment]
Thank you, ticked off this one and Step 3 is considered done (if I didn't miss something)

**Comment by kytrinyx** [comment]
@m-a-ge I noticed that you asked to join the track-maintainers team. You're already a member of this team by virtue of being a member of the exercism/groovy team. We are using nested teams, so nobody is directly a member of track-maintainers.

**Comment by m-a-ge** [comment]
ah, sorry @kytrinyx , please ignore

**Comment by amscotti** [comment]
Closing this issue as Groovy is now launched on the site with the merging of PR #150
